version: '3'

services:
  master:
    image: mjhea0/spark:2.4.1
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080

  worker:
    image: wacosta/spark-custom:2.4.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    depends_on:
      - master
    ports:
      - 8081:8081
    volumes:
      - london-power:/usr/spark-2.4.1/volume

  hadoop:
    image: harisekhon/hadoop:2.8
    hostname: hadoop
    ports:
      #- 8020:8020
      - 8042:8042
      - 8088:8088
      #- 9000:9000
      #- 10020:10020
      - 19888:19888
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 50090:50090

  jupyter:
    image: jupyter/pyspark-notebook:f646d2b2a3af
    volumes:
      - london-power:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - JUPYTER_TOKEN

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    image: mongo-express
    ports:
      - 8181:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD

volumes:
  london-power:
    external: true

networks:
  default:
    external:
      name: spark-network
