version: '3'

services:
  jupyter:
    image: jupyter/pyspark-notebook:f646d2b2a3af
    volumes:
      - jupyter-data:/home/jovyan/work
    ports:
      - 8888:8888

volumes:
  jupyter-data:
    external: true

networks:
  default:
    external:
      name: spark-network
