version: '3'

services:
  jupyter:
    image: jupyter/pyspark-notebook:f646d2b2a3af
    volumes:
      - jupyter-data:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}


volumes:
  jupyter-data:
    external: true

networks:
  default:
    external:
      name: spark-network
